### ISSUE TITLE
Minimum hardware requirements 

### ISSUE THREAD

**Issue by basilboli** [zphang/minimal-gpt-neox-20b#6]
Hi guys, 
thanks for the implementation. 
I am trying to run the model on the server with NVIDIA RTX A6000 (GPU Memory
48 GB GDDR6) but it fails. 

Other server characteristics: 
1 GPU - 4 vCPUs - 16 Gi RAM

Do you have any minimum hardware requirements, so I can play with the model ? 

Thanks.

**Comment by basilboli** [comment]
Update: I have tried to add more RAM (~90 GB) to the server, and it worked.

Note: It failed with error "NVIDIA RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation"

```
Instantiating model (~1 min):   0%|                                                                                                                                                                                  | 0/48 [00:00<?, ?it/s]/home/basilboli/.local/lib/python3.10/site-packages/torch/cuda/__init__.py:146: UserWarning: 
NVIDIA RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA RTX A6000 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Loading layer 36:  77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                         | 37/48 [02:07<00:07,  1.43it/s]Traceback (most recent call last):
  File "/home/basilboli/minimal-gpt-neox-20b/demo.py", line 3, in <module>
    model = minimal20b.create_model(
  File "/home/basilboli/minimal-gpt-neox-20b/minimal20b/create.py", line 34, in create_model
    loaded_tp2 = torch.load(os.path.join(checkpoint_path, filename_tp2))
  File "/home/basilboli/.local/lib/python3.10/site-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/basilboli/.local/lib/python3.10/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
Loading layer 36:  77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                         | 37/48 [02:07<00:38,  3.45s/it]


```
But I will open a separate issue for this.

**Comment by basilboli** [comment]
I had problems installing capability sm_86 on Ubuntu 22.02.
I have switched to Ubuntu 20.02 and installed sm_86 using command:
```
pip3 install torch torchvision torchaudio --force-reinstall  --extra-index-url https://download.pytorch.org/whl/cu116
```
It has fixed the issue.
